version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  unit-test: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.16
        auth:
          username: mammadmodi
          password: $DOCKERHUB_TOKEN  # context / project UI env-var reference

    parallelism: 2

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run: make mock # create mock files which is needed in unit tests

      - run:
          name: Run unit tests
          # store the results of our tests in the $TEST_RESULTS directory
          command: |
            go test --race -gcflags=-l -v -coverprofile ${TEST_RESULTS}/coverage.out ./...
            go tool cover -func ${TEST_RESULTS}/coverage.out
      - run: ls
workflows:
  version: 2
  test:
    jobs:
      - unit-test